# Configuración de Fine-Tuning para ResNet50 - CLASIFICACIÓN
# Este archivo está optimizado para clasificación tradicional con CrossEntropy

# ===== DATASET =====
views: ['front']
class_granularity: 'model+year'
min_train_images: 4
min_val_images: 3
min_test_images: 3
seed: 3

# Zero-shot testing
enable_zero_shot: True
num_zero_shot_classes: 100

# ===== TRANSFORMACIONES =====
image_size: [224, 224]
grayscale: true
use_bbox: true
augment: true

# ===== MODELO =====
model_type: 'vision'
model_name: 'resnet50'
weights: 'IMAGENET1K_V1'
objective: 'ArcFace' 

# ===== TRAINING =====
P: 32
K: 4
batch_size: 128 
num_workers: 0
pin_memory: true
device: 'cuda'

# Fine-tuning
finetune_epochs: 120
finetune_criterion: 'CrossEntropyLoss'
finetune_optimizer_type: 'AdamW'
finetune_backbone_lr: 8.0e-6 
finetune_head_lr: 3.0e-4
finetune_optimizer_weight_decay: 1.5e-2  

# Scheduler
use_scheduler: true
scheduler_type: 'cosine_warmup'
warmup_epochs: 30

# Early stopping
use_early_stopping: true
patience: 35

# Gradient clipping
gradient_clip_value: 1.0

# Mixed precision training
use_amp: true
